CREATE TABLE "tickets" (
	"id" serial PRIMARY KEY NOT NULL,
	"ticket_number" text NOT NULL,
	"title" text NOT NULL,
	"category" text NOT NULL,
	"priority" text DEFAULT 'Medium' NOT NULL,
	"status" text DEFAULT 'Pending' NOT NULL,
	"customer_name" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_nin" text,
	"customer_bvn" text,
	"merchant_name" text,
	"assigned_officer" text,
	"imei_validation_required" boolean DEFAULT false NOT NULL,
	"correct_imei" text,
	"incorrect_imei" text,
	"portal_imei" text,
	"device_imei" text,
	"validation_result" text,
	"imei_reason" text,
	"old_imei" text,
	"new_imei" text,
	"device_change_reason" text,
	"loan_amount" numeric(14, 2),
	"outstanding_balance" numeric(14, 2),
	"due_balance" numeric(14, 2),
	"loan_status" text,
	"loan_date" date,
	"due_date" date,
	"description" text NOT NULL,
	"steps_to_reproduce" text,
	"expected_result" text,
	"actual_result" text,
	"troubleshooting" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"attachments" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"root_cause" text,
	"resolution" text,
	"escalated_to" text,
	"ai_recommendations" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"approvals" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"first_response_minutes" integer,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tickets_ticket_number_unique" UNIQUE("ticket_number")
);
