/** Credlock Technical Support - Google Sheets + Apps Script backend. */
const TZ='Africa/Lagos';
const CONFIG_KEY='CREDLOCK_SPREADSHEET_ID';
const SESSION_TTL=21600;

const SCHEMA={
'Users':['Record ID','Email','First Name','Last Name','Role','Photo','Date Created','Status','Department'],
'Auth Users':['Record ID','Email','Password Hash','Role','Status','Department','Date Created','Last Login'],
'Departments':['Record ID','Department Name','Manager Email','Users','Issue Categories','Officers','Issues','BNPL Applications','Incidents','Internal Requests','Monthly Evaluations'],
'Issue Categories':['Record ID','Category Name','Priority Level','Default Department','Issues'],
'Officers':['Record ID','Officer Name','Email','Department','Role','Issues','Status'],
'Issues':['Record ID','Issue Title','Description','Category','Department','Reported By Email','Assigned Officer','Priority','Status','Date Created','First Response Time','Date Resolved','Feedback','Customer Name','NIN Number','Incidents','Todo Items','Source','Contact Phone','Has Foneflex Loan','Rejection Reason','Foneflex Request Type','Subject Type','Action Reason','Crime Book Logged','Ticket ID','SLA Target (Minutes)','FRT Minutes','Resolution Minutes','SLA Met','Resolution Notes','Root Cause','Escalation Required','Escalation Level','Ticket Closed At','Channel','Customer / Merchant Phone','Customer Device / IMEI','Customer Loan / Application Reference','Reopen Count','Attachment URLs'],
'Feedback':['Record ID','Feedback ID','Issue','Message','Sender Email','Sender Type','Date Sent'],
'Meetings':['Record ID','Meeting Title','Meeting Date','Meeting Type','Status','Meeting Notes','Created By Email','Created At'],
'Meeting Items':['Record ID','Topic','Meeting','Item Type','Details','Status','Priority','Added By','Date Added'],
'AuditLog':['Record ID','Action','Performed By','Affected Record','Affected Table','Reason','Old Value','New Value','Timestamp','Severity'],
'Incidents':['Record ID','Incident Title','Severity','Incident Type','Status','Department','Linked Ticket','Impact Description','Resolution Notes','Date Reported','Date Resolved','Assigned To Email'],
'Todo Items':['Record ID','Task','Priority','Status','Assigned To','Created By','Due Date','Notes','Date Created','Related Ticket','Is Personal'],
'Page Permissions':['Record ID','Page Key','Allowed Roles','Allowed Actions','Updated By','Updated At'],
'Internal Requests':['Record ID','Request Title','Status','Requested By Email','Requested By Name','Department','Amount','Description','Reviewed By','Review Notes','Date Submitted','Date Reviewed'],
'Knowledge Base Articles':['Record ID','Title','Category','Severity','Tags','Steps','Response Template','Escalation Path','Created By Email','Date Created'],
'Recovery Records':['Record ID','Device Name','Serial Number','IMEI Number','Device Type','Customer Name','Customer Phone','Recovery Status','Recovered By Email','Recovered By Name','Recovery Date','Notes','Location Found','Date Logged'],
'Recovery Tasks':['Record ID','Task Title','Description','Status','Priority','Assigned To Email','Assigned To Name','Assigned By Email','Due Date','Date Assigned','Notes'],
'Monthly Evaluations':['Record ID','Evaluation ID','Team Lead Name','Month','Year','Team Member Name','Team Member Email','Customers Assisted','Merchants Assisted','Technical Issues Resolved','Accounts Unlocked','Issues Escalated','Additional Notes','Status','Submitted By Email','Submitted By Name','Department','Reviewed By','Review Notes','Date Submitted','Date Reviewed','AI Score','AI Summary','Avg Response Time','CSAT','NPS','FCR','Tickets Closed','Tickets Reopened','Live Chat Interactions','Voice Calls','Devices Enrolled','Devices Wiped','Device Compliance','App Installations','MDM Policy Violations','Remote Lock Unlock','Loan Apps Processed','Loan Approvals','Loan Rejections','Collections Follow Ups','Reversals Processed','Defaults Overdues Managed','Credit Adjustments','KB Articles Updated','Training Attended','Process Improvements','Compliance Audits Passed','Errors Reported','New Merchants Onboarded','New Customers Registered','Upsell Cross Sell','Revenue Influenced'],
'Staff Schedules':['Record ID','Schedule Title','Employee Email','Employee Name','Department Name','Date','Day Type','Shift','Start Time','End Time','Notes','Approved By','Submitted By Email','Date Created','Week Number','Year'],
'Pending Questions':['Record ID','Question','Language','Asked By Name','Status','Answer','Answered By','Source','Date Asked'],
'Broadcasts':['Record ID','Title','Message','Type','Target','Created By Email','Is Active','Expires At','Date Created'],
'KPI Targets':['Record ID','Target Name','Target Value','Unit','Category','Description','Last Updated'],
'Manual Reports':['Record ID','Report Date','Officer Name','BNPL Reviewed','BNPL Ongoing','BNPL Pending','BNPL Rejected','Customers Assisted','Merchants Assisted','Calls Chats','Customers Unlocked','Training Support','Merchant Complaints','Technical Issues','Operational Challenge','Recommendations','Period Breakdown','Uploaded Documents','Submitted By','Created At'],
'BNPL Applications':['Record ID','Application Reference','Customer Name','Customer Phone','Merchant Name','Device','IMEI','Amount','Status','Assigned Officer','Submitted At','Reviewed At','Rejection Reason','Department'],
'Operational Blueprints':['Record ID','Title','Content','Version','Last Updated']
};
const SELECTS={Role:['ADMIN','EMPLOYEE','BUSINESS MANAGER','TECHNICAL SUPPORT OFFICER','HR','OFFICER'],UserStatus:['ACTIVE','INACTIVE'],Priority:['HIGH','MEDIUM','LOW'],IssueStatus:['OPEN','IN_PROGRESS','PENDING','RESOLVED','CLOSED','REOPENED'],Source:['Web Portal','WhatsApp','Email','Phone','Walk-In','SYSTEM_CREATE','AI Assistant','Merchant Support Portal'],SubjectType:['Customer','Merchant'],FoneflexRequestType:['Unlock Request','Lock Request','Removal Request'],EscalationLevel:['L1','L2','L3','MANAGEMENT'],IncidentStatus:['OPEN','INVESTIGATING','RESOLVED','CLOSED'],TaskStatus:['Assigned','In Progress','Completed','Cancelled'],BroadcastType:['INFO','ALERT','MAINTENANCE','POLICY','TRAINING'],Target:['ALL','OFFICERS','MERCHANTS','CUSTOMERS','MANAGERS','ADMIN']};

function setupBackend(){
 const existingId=PropertiesService.getScriptProperties().getProperty(CONFIG_KEY); const ss=existingId?SpreadsheetApp.openById(existingId):SpreadsheetApp.create('Credlock Technical Support Ticketing Backend'); PropertiesService.getScriptProperties().setProperty(CONFIG_KEY,ss.getId());
 Object.keys(SCHEMA).forEach(name=>{let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);const headers=SCHEMA[name];const current=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0]:[];if(!current.length||current.every(v=>!v))sh.getRange(1,1,1,headers.length).setValues([headers]);else if(current.join('|')!==headers.join('|')){sh.clear();sh.getRange(1,1,1,headers.length).setValues([headers]);}sh.setFrozenRows(1);sh.getRange(1,1,1,headers.length).setFontWeight('bold');});
 seedDefaults(ss); return {ok:true,spreadsheetId:ss.getId(),url:ss.getUrl(),sheets:Object.keys(SCHEMA)};
}
function seedDefaults(ss){const seed=(name,rows)=>{const sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()>1)return;const h=SCHEMA[name];sh.getRange(2,1,rows.length,h.length).setValues(rows.map(r=>h.map(k=>r[k]??'')));};
 seed('Departments',[{'Record ID':'DEP-TECH','Department Name':'Technical Support'},{'Record ID':'DEP-COL','Department Name':'Collections'}]);
 seed('Issue Categories',[{'Record ID':'CAT-APP','Category Name':'App / Login Issue','Priority Level':'HIGH','Default Department':'Technical Support'},{'Record ID':'CAT-DEVICE','Category Name':'Device / IMEI','Priority Level':'HIGH','Default Department':'Technical Support'},{'Record ID':'CAT-BNPL','Category Name':'BNPL Operations','Priority Level':'MEDIUM','Default Department':'Technical Support'},{'Record ID':'CAT-MERCHANT','Category Name':'Merchant Support','Priority Level':'MEDIUM','Default Department':'Technical Support'},{'Record ID':'CAT-PAYMENT','Category Name':'Payment / Reversal','Priority Level':'HIGH','Default Department':'Technical Support'}]);
 seed('Page Permissions',[{'Record ID':'PERM-DASH','Page Key':'dashboard','Allowed Roles':'ADMIN,TECHNICAL SUPPORT OFFICER,BUSINESS MANAGER,HR','Allowed Actions':'read'},{'Record ID':'PERM-TICKETS','Page Key':'tickets','Allowed Roles':'ADMIN,TECHNICAL SUPPORT OFFICER,BUSINESS MANAGER,OFFICER','Allowed Actions':'read,create,update'},{'Record ID':'PERM-ADMIN','Page Key':'admin','Allowed Roles':'ADMIN','Allowed Actions':'read,create,update,delete'}]);
}

function doGet(e){try{const p=e&&e.parameter?e.parameter:{};const action=p.action||'health';if(action==='health')return json({ok:true,service:'credlock-ticketing',timezone:TZ,time:now(),version:'apps-script-sheets-primary'});const session=requireSession(p.token);const ss=getSpreadsheet();if(action==='metadata')return json({ok:true,schema:SCHEMA,selects:SELECTS});if(action==='session')return json({ok:true,authenticated:true,user:session.user});if(action==='dashboard')return json({ok:true,metrics:getMetrics(ss),tickets:listRecords(ss,'Issues',p.limit||50)});if(action==='tickets')return json({ok:true,metrics:getMetrics(ss),tickets:listRecords(ss,'Issues',p.limit||200)});if(action==='list')return json({ok:true,table:p.table,records:listRecords(ss,p.table,p.limit||500)});if(action==='get')return json({ok:true,record:getRecord(ss,p.table,p.id)});return json({ok:false,error:'Unknown action'});}catch(err){return json({ok:false,error:String(err)})}}

function doPost(e){try{const body=parseBody(e);const action=body.action||'create';if(action==='login')return login(body.email,body.password);if(action==='setup')return json(setupBackend());const session=requireSession(body.token);const ss=getSpreadsheet();if(action==='logout'){CacheService.getScriptCache().remove('sess_'+body.token);return json({ok:true});}if(action==='create'){requirePermission(session,'create',body.table);return json({ok:true,record:createRecord(ss,body.table,body.record||{},session.user.Email)})}if(action==='update'){requirePermission(session,'update',body.table);return json({ok:true,record:updateRecord(ss,body.table,body.id,body.record||{},session.user.Email)})}if(action==='delete'){requirePermission(session,'delete',body.table);return json({ok:true,deleted:deleteRecord(ss,body.table,body.id,session.user.Email)})}if(action==='ticketAction'){requirePermission(session,'update','Issues');return json({ok:true,record:ticketAction(ss,body.id,body.ticketAction,body.payload||{},session.user.Email)})}if(action==='upload'){requirePermission(session,'create','Issues');return json({ok:true,file:saveAttachment(body)})}return json({ok:false,error:'Unknown action'});}catch(err){return json({ok:false,error:String(err)})}}

function createAuthUser(email,password,role,department){if(!email||!password)throw new Error('Email and password are required');const ss=getSpreadsheet();const sh=getSheet(ss,'Auth Users');const existing=listRecords(ss,'Auth Users',5000).find(r=>String(r.Email).toLowerCase()===String(email).trim().toLowerCase());if(existing)throw new Error('Auth user already exists');const rec={'Record ID':makeId('AUTH'),'Email':String(email).trim().toLowerCase(),'Password Hash':hashPassword(password),'Role':role||'EMPLOYEE','Status':'ACTIVE','Department':department||'Technical Support','Date Created':now()};sh.appendRow(SCHEMA['Auth Users'].map(h=>normalizeCell(rec[h])));return rec}
function login(email,password){if(!email||!password)throw new Error('Email and password are required');const ss=getSpreadsheet();const users=listRecords(ss,'Auth Users',5000);const u=users.find(r=>String(r.Email).toLowerCase()===String(email).trim().toLowerCase());if(!u||String(u.Status).toUpperCase()!=='ACTIVE'||String(u['Password Hash'])!==hashPassword(password))throw new Error('Invalid email or password.');const token=Utilities.getUuid()+'-'+Utilities.getUuid();const user={'Record ID':u['Record ID'],'Email':u.Email,'Role':u.Role,'Status':u.Status,'Department':u.Department};CacheService.getScriptCache().put('sess_'+token,JSON.stringify({user}),SESSION_TTL);const sh=getSheet(ss,'Auth Users');const values=sh.getDataRange().getValues();const idx=values[0].indexOf('Record ID');const row=values.slice(1).findIndex(r=>String(r[idx])===String(u['Record ID']));if(row>=0)sh.getRange(row+2,values[0].indexOf('Last Login')+1).setValue(now());return json({ok:true,token,user})}
function requireSession(token){if(!token)throw new Error('Authentication required.');const raw=CacheService.getScriptCache().get('sess_'+token);if(!raw)throw new Error('Session expired. Please sign in again.');return JSON.parse(raw)}
function requirePermission(session,action,table){if(action==='delete'&&String(session.user.Role).toUpperCase()!=='ADMIN')throw new Error('Administrator permission required for deletion.');if(table==='Auth Users'&&String(session.user.Role).toUpperCase()!=='ADMIN')throw new Error('Administrator permission required.')}
function hashPassword(password){const digest=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(password),Utilities.Charset.UTF_8);return digest.map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('')}

function getSpreadsheet(){const id=PropertiesService.getScriptProperties().getProperty(CONFIG_KEY);if(!id)throw new Error('Backend is not initialized. Run setupBackend() once.');return SpreadsheetApp.openById(id)}
function listRecords(ss,table,limit){const sh=getSheet(ss,table);const values=sh.getDataRange().getValues();if(values.length<2)return[];const headers=values.shift();return values.filter(r=>r.some(v=>v!=='')).slice(0,Number(limit)||500).map(r=>rowToObject(headers,r))}
function getRecord(ss,table,id){const sh=getSheet(ss,table);const values=sh.getDataRange().getValues();if(!values.length)return null;const headers=values[0];const idx=headers.indexOf('Record ID');const row=values.slice(1).find(r=>String(r[idx])===String(id));return row?rowToObject(headers,row):null}
function createRecord(ss,table,record,actor){const sh=getSheet(ss,table);const headers=SCHEMA[table];const out=Object.assign({},record);if(!out['Record ID'])out['Record ID']=makeId(table);if(table==='Issues'){if(!out['Ticket ID'])out['Ticket ID']=nextTicketId(sh);if(!out['Date Created'])out['Date Created']=now();if(!out.Status)out.Status='OPEN';if(!out['Reopen Count'])out['Reopen Count']=0}if(table==='AuditLog'&&!out.Timestamp)out.Timestamp=now();if(table==='Feedback'&&!out['Feedback ID'])out['Feedback ID']=nextNumericId(sh,'Feedback ID');const row=headers.map(h=>normalizeCell(out[h]));sh.appendRow(row);if(table==='Issues')writeDerivedTicketMetrics(sh,sh.getLastRow());writeAudit('CREATE',table,out['Record ID'],'',JSON.stringify(out),'MEDIUM',actor);return rowToObject(headers,row)}
function updateRecord(ss,table,id,record,actor){const sh=getSheet(ss,table);const values=sh.getDataRange().getValues();const headers=values[0];const idx=headers.indexOf('Record ID');const rowIndex=values.slice(1).findIndex(r=>String(r[idx])===String(id));if(rowIndex<0)throw new Error('Record not found');const actual=rowIndex+2;const old=rowToObject(headers,values[actual-1]);const next=Object.assign({},old,record);sh.getRange(actual,1,1,headers.length).setValues([headers.map(h=>normalizeCell(next[h]))]);if(table==='Issues')writeDerivedTicketMetrics(sh,actual);writeAudit('UPDATE',table,id,JSON.stringify(old),JSON.stringify(next),'MEDIUM',actor);return rowToObject(headers,headers.map(h=>normalizeCell(next[h])))}
function deleteRecord(ss,table,id,actor){const sh=getSheet(ss,table);const values=sh.getDataRange().getValues();const idx=values[0].indexOf('Record ID');const rowIndex=values.slice(1).findIndex(r=>String(r[idx])===String(id));if(rowIndex<0)return false;sh.deleteRow(rowIndex+2);writeAudit('DELETE',table,id,'','HIGH',actor);return true}
function ticketAction(ss,id,action,payload,actor){const current=getRecord(ss,'Issues',id)||{};const updates={};switch(action){case'assign':updates['Assigned Officer']=payload.officer||payload.assignedOfficer||'';break;case'respond':updates.Status='IN_PROGRESS';if(!current['First Response Time'])updates['First Response Time']=payload.firstResponseTime||now();break;case'pending':updates.Status='PENDING';break;case'resolve':updates.Status='RESOLVED';updates['Resolution Notes']=payload.notes||payload.resolutionNotes||'';updates['Root Cause']=payload.rootCause||'';updates['Date Resolved']=payload.dateResolved||now();break;case'close':updates.Status='CLOSED';updates['Ticket Closed At']=payload.closedAt||now();break;case'reopen':updates.Status='REOPENED';updates['Reopen Count']=Number(current['Reopen Count']||0)+1;break;case'escalate':updates['Escalation Required']='YES';updates['Escalation Level']=payload.level||payload.escalationLevel||'L2';break;default:throw new Error('Unsupported ticket action: '+action)}return updateRecord(ss,'Issues',id,updates,actor)}
function getMetrics(ss){const tickets=listRecords(ss,'Issues',5000);const active=tickets.filter(t=>['OPEN','IN_PROGRESS','PENDING','REOPENED'].includes(String(t.Status).toUpperCase()));const closed=tickets.filter(t=>['CLOSED','RESOLVED'].includes(String(t.Status).toUpperCase()));const critical=tickets.filter(t=>String(t.Priority).toUpperCase()==='HIGH'&&!['CLOSED','RESOLVED'].includes(String(t.Status).toUpperCase()));const frt=tickets.map(t=>Number(t['FRT Minutes'])).filter(Number.isFinite);const res=tickets.map(t=>Number(t['Resolution Minutes'])).filter(Number.isFinite);const sla=closed.filter(t=>String(t['SLA Met']).toUpperCase()==='TRUE');const categories={};tickets.forEach(t=>{const k=t.Category||'Uncategorized';categories[k]=(categories[k]||0)+1});return{total:tickets.length,open:active.length,pending:tickets.filter(t=>String(t.Status).toUpperCase()==='PENDING').length,closed:closed.length,critical:critical.length,slaCompliance:closed.length?Math.round(sla.length/closed.length*100):100,resolutionTime:res.length?Math.round(res.reduce((a,b)=>a+b,0)/res.length/60*10)/10:0,firstResponseTime:frt.length?Math.round(frt.reduce((a,b)=>a+b,0)/frt.length):0,imeiValidation:tickets.filter(t=>t['Customer Device / IMEI']&&!['CLOSED','RESOLVED'].includes(String(t.Status).toUpperCase())).length,recurringIssues:Object.keys(categories).filter(k=>categories[k]>1).length,reopened:tickets.reduce((n,t)=>n+(Number(t['Reopen Count'])||0),0)}}
function writeDerivedTicketMetrics(sh,row){const headers=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];const values=sh.getRange(row,1,1,sh.getLastColumn()).getValues()[0];const get=k=>values[headers.indexOf(k)];const set=(k,v)=>{const i=headers.indexOf(k);if(i>=0)sh.getRange(row,i+1).setValue(v)};const created=dateValue(get('Date Created'));const response=dateValue(get('First Response Time'));const resolved=dateValue(get('Date Resolved')||get('Ticket Closed At'));if(created&&response)set('FRT Minutes',Math.max(0,(response-created)/60000));if(created&&resolved)set('Resolution Minutes',Math.max(0,(resolved-created)/60000));const target=Number(get('SLA Target (Minutes)'))||1440;const resolution=Number(get('Resolution Minutes'));if(resolution)set('SLA Met',resolution<=target)}
function writeAudit(action,table,id,oldValue,newValue,severity,actor){try{const ss=getSpreadsheet();const sh=ss.getSheetByName('AuditLog');if(!sh)return;const rec={'Record ID':makeId('AUD'),'Action':action,'Performed By':actor||'SYSTEM','Affected Record':id,'Affected Table':table,'Reason':'API operation','Old Value':oldValue,'New Value':newValue,'Timestamp':now(),'Severity':severity};sh.appendRow(SCHEMA.AuditLog.map(h=>normalizeCell(rec[h])))}catch(_) {}}
function saveAttachment(body){if(!body||!body.data)throw new Error('Attachment data is required');const bytes=Utilities.base64Decode(String(body.data).split(',').pop());const blob=Utilities.newBlob(bytes,body.mimeType||'application/octet-stream',body.name||('attachment-'+Date.now()));const folders=DriveApp.getFoldersByName('Credlock Ticket Attachments');const folder=folders.hasNext()?folders.next():DriveApp.createFolder('Credlock Ticket Attachments');const file=folder.createFile(blob);return{name:file.getName(),url:file.getUrl(),id:file.getId()}}
function parseBody(e){const raw=e&&e.postData&&e.postData.contents?e.postData.contents:'{}';try{return JSON.parse(raw)}catch(_){return e.parameter||{}}}
function getSheet(ss,name){if(!SCHEMA[name])throw new Error('Unsupported table: '+name);const sh=ss.getSheetByName(name);if(!sh)throw new Error('Missing sheet: '+name+'. Run setupBackend().');return sh}
function rowToObject(headers,row){const out={};headers.forEach((h,i)=>out[h]=row[i] instanceof Date?Utilities.formatDate(row[i],TZ,"yyyy-MM-dd'T'HH:mm:ssXXX"):row[i]);return out}
function normalizeCell(v){if(v===null||v===undefined)return'';if(Array.isArray(v))return v.join(', ');if(typeof v==='object')return JSON.stringify(v);return v}
function dateValue(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?null:d.getTime()}
function now(){return Utilities.formatDate(new Date(),TZ,"yyyy-MM-dd'T'HH:mm:ssXXX")}
function makeId(prefix){return prefix.replace(/[^A-Z0-9]/gi,'').slice(0,5).toUpperCase()+'-'+Utilities.getUuid().slice(0,8).toUpperCase()}
function nextNumericId(sh,header){const values=sh.getDataRange().getValues();const i=values[0].indexOf(header);return Math.max(0,...values.slice(1).map(r=>Number(r[i])||0))+1}
function nextTicketId(sh){return nextNumericId(sh,'Ticket ID')}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}
